### ISSUE TITLE
Click action in dashboard do not work with LH Task Exception

### ISSUE THREAD

**Issue by KarlaCarvajal** [littlehorse-enterprises/littlehorse#1068]
### Context

Testing the Shopping Order Flow [repo](https://github.com/littlehorse-enterprises/doodles/tree/master/doodles/lh-demo) and trying to see the exception, it was not possible to check the detail in the **Inspect Task Run link**

**Workflow run command:**
`lhctl run shopping order-input "{\"order_id\":\"123\",\"total_cost\":101,\"customer\":{\"id\":\"customer-1\"},\"items\":[{\"name\":\"lipstick\",\"quantity\":1,\"price\":5.25},{\"name\":\"eye-mask\",\"quantity\":2,\"price\":12.86}]}"`
**Evidence:**
https://github.com/user-attachments/assets/fd9fa4f4-48ce-47ea-b491-4607b40dbcf7

### Steps To Reproduce

Go to the dashboard
Click on Inspect Task Run link

### Expected Behavior

The click action should show the screen with the exception detail

### Screenshots

![image](https://github.com/user-attachments/assets/ac36299d-066c-49c3-be72-424d96ad9d90)

**Comment by mijailr** [comment]
Related to #853, I'll reopen that one.

**Comment by HazimAr** [comment]
This is not a dashboard issue. The server returns and empty object for `task` so the dashboard can't open the modal due to `if (!null) return`.

**Comment by mijailr** [comment]
> This is not a dashboard issue. The server returns and empty object for `task` so the dashboard can't open the modal due to `if (!null) return`.
> 
> If we decide on a different architecture then the dashboard will need to change.


The dashboard shouldn't render the "Inspect Task Run" when the nodeRun has no task.
