### ISSUE TITLE
Delete task run when deleting the wf run

### ISSUE THREAD

**Issue by sauljabin** [littlehorse-enterprises/littlehorse#1077]
### Context

Right now after deleting the wf run the task run is still visible

### Steps To Reproduce

Run a workflow with a user task then remove the wf run:

` lhctl delete wfRun 1f98b2488e474fd8925f86156e2c8d89`

### Expected Behavior

Remove the task run alongside the wf run

### Screenshots

The workflow was remove but the task is there (this is not expected):
![image](https://github.com/user-attachments/assets/a62e3c07-994a-42fe-b5d9-a08725e43142)

On clicking the wf run id it is not found (this is expected)
![image](https://github.com/user-attachments/assets/ac25ec53-1442-4924-94b3-ac75bdcdf777)

### Components

Server

**Comment by coltmcnealy-lh** [comment]
This should delete _all_ `WfRun`-scoped objects, including:
* `TaskRun`
* `Variable`
* `ExternalEvent`
* `UserTaskRun`
* `WorkflowEvent`
* `NodeRun`

The easiest way to implement is is inside `DeleteWfRunRequestModel#process()` using the `GetableManager#delete(ObjectIdModel<?, ?, ?>)` method.

CC @Snarr
