### ISSUE TITLE
Dashboard: Handle Multiple NodeRun's on One Node

### ISSUE THREAD

**Issue by muhammadqamar** [littlehorse-enterprises/littlehorse#1092]
Currently, on the dashboard, the task node behaves inconsistently when there are multiple TaskRuns associated with a single task node. When a user clicks on the node and expands to inspect the TaskRun, only information for a single, random TaskRun is displayed.

![Image](https://github.com/user-attachments/assets/d6a6f9d3-9453-4ea8-a8a9-685e57993020)

**Expected Behavior:**

When there are multiple TaskRuns for a task node, we should improve the user experience by:
1. Hiding the task arguments (args) 
2. Displaying a paginated list of all TaskRuns associated with the task node.
3. Making each TaskRun in the list clickable, which will navigate the user to a new route (e.g., `/wfrun/:id/taskrun/:id`).

**Proposed Solution:**

- When multiple TaskRuns exist for a task node, replace the current TaskRun details with a list of TaskRuns.
- The list should have pagination controls to manage large sets of TaskRuns.
- Each TaskRun should be clickable, and clicking on it should lead to a dedicated page for that TaskRun with detailed information. The URL for each TaskRun page would follow the format: `/wfrun/:id/taskrun/:id`.
- On the TaskRun detail page, display comprehensive details about the selected TaskRun,  logs, status, variable info and other relevant information.

This will make it easier for users to navigate and inspect the details of multiple TaskRuns without being overwhelmed by excessive information on the Task node view.

**Comment by muhammadqamar** [comment]
> This ticket is about any case in which a single `Node` can have multiple `NodeRun`s in a `ThreadRun`. There are two cases right now which cause this:
> 
> 1. A loop in the `ThreadSpec`
> 2. Using `rpc RescueThreadRun` which causes the failed `NodeRun` to be run again.
> 
> Therefore I think the title of the ticket is wrong. We don't want to show multiple `TaskRun`s. We want to show multiple `NodeRun`s which occurred for the same `Node`. The `NodeRun`s should be ordered by the position field: lower position means they were created first.

Thanks @coltmcnealy-lh.
me and @mijailr had a detail call again on that and we discussed couple of use cases and also some limitation as well. we will share shortly

**Comment by HazimAr** [comment]
closed by #1113
