### ISSUE TITLE
Throw Business-Level `EXCEPTION`s in DotNet Task Worker

### ISSUE THREAD

**Issue by coltmcnealy-lh** [littlehorse-enterprises/littlehorse#1094]
Follow this documentation: https://littlehorse.dev/docs/developer-guide/task-worker-development#throwing-workflow-exceptions

**Comment by KarlaCarvajal** [comment]
This is the wfSpec for the test

`<pre>{
  &quot;id&quot;:  {
    &quot;name&quot;:  &quot;example-exception-handler&quot;,
    &quot;majorVersion&quot;:  0,
    &quot;revision&quot;:  3
  },
  &quot;createdAt&quot;:  &quot;2024-11-27T21:38:53.236Z&quot;,
  &quot;frozenVariables&quot;:  [],
  &quot;status&quot;:  &quot;ACTIVE&quot;,
  &quot;threadSpecs&quot;:  {
    &quot;entrypoint&quot;:  {
      &quot;nodes&quot;:  {
        &quot;0-entrypoint-ENTRYPOINT&quot;:  {
          &quot;outgoingEdges&quot;:  [
            {
              &quot;sinkNodeName&quot;:  &quot;1-fail-TASK&quot;,
              &quot;variableMutations&quot;:  []
            }
          ],
          &quot;failureHandlers&quot;:  [],
          &quot;entrypoint&quot;:  {}
        },
        &quot;1-fail-TASK&quot;:  {
          &quot;outgoingEdges&quot;:  [
            {
              &quot;sinkNodeName&quot;:  &quot;2-fail-new-process-TASK&quot;,
              &quot;variableMutations&quot;:  []
            }
          ],
          &quot;failureHandlers&quot;:  [
            {
              &quot;handlerSpecName&quot;:  &quot;exn-handler-1-fail-TASK-null&quot;,
              &quot;anyFailureOfType&quot;:  &quot;FAILURE_TYPE_EXCEPTION&quot;
            }
          ],
          &quot;task&quot;:  {
            &quot;taskDefId&quot;:  {
              &quot;name&quot;:  &quot;fail&quot;
            },
            &quot;timeoutSeconds&quot;:  15,
            &quot;retries&quot;:  0,
            &quot;variables&quot;:  []
          }
        },
        &quot;2-fail-new-process-TASK&quot;:  {
          &quot;outgoingEdges&quot;:  [
            {
              &quot;sinkNodeName&quot;:  &quot;3-technical-failure-TASK&quot;,
              &quot;variableMutations&quot;:  []
            }
          ],
          &quot;failureHandlers&quot;:  [
            {
              &quot;handlerSpecName&quot;:  &quot;exn-handler-2-fail-new-process-TASK-any-failure&quot;
            }
          ],
          &quot;task&quot;:  {
            &quot;taskDefId&quot;:  {
              &quot;name&quot;:  &quot;fail-new-process&quot;
            },
            &quot;timeoutSeconds&quot;:  15,
            &quot;retries&quot;:  0,
            &quot;variables&quot;:  []
          }
        },
        &quot;3-technical-failure-TASK&quot;:  {
          &quot;outgoingEdges&quot;:  [
            {
              &quot;sinkNodeName&quot;:  &quot;4-my-task-TASK&quot;,
              &quot;variableMutations&quot;:  []
            }
          ],
          &quot;failureHandlers&quot;:  [
            {
              &quot;handlerSpecName&quot;:  &quot;exn-handler-3-technical-failure-TASK-FAILURE_TYPE_ERROR&quot;,
              &quot;anyFailureOfType&quot;:  &quot;FAILURE_TYPE_ERROR&quot;
            }
          ],
          &quot;task&quot;:  {
            &quot;taskDefId&quot;:  {
              &quot;name&quot;:  &quot;technical-failure&quot;
            },
            &quot;timeoutSeconds&quot;:  15,
            &quot;retries&quot;:  0,
            &quot;variables&quot;:  []
          }
        },
        &quot;4-my-task-TASK&quot;:  {
          &quot;outgoingEdges&quot;:  [
            {
              &quot;sinkNodeName&quot;:  &quot;5-exit-EXIT&quot;,
              &quot;variableMutations&quot;:  []
            }
          ],
          &quot;failureHandlers&quot;:  [],
          &quot;task&quot;:  {
            &quot;taskDefId&quot;:  {
              &quot;name&quot;:  &quot;my-task&quot;
            },
            &quot;timeoutSeconds&quot;:  15,
            &quot;retries&quot;:  0,
            &quot;variables&quot;:  []
          }
        },
        &quot;5-exit-EXIT&quot;:  {
          &quot;outgoingEdges&quot;:  [],
          &quot;failureHandlers&quot;:  [],
          &quot;exit&quot;:  {}
        }
      },
      &quot;variableDefs&quot;:  [],
      &quot;interruptDefs&quot;:  []
    },
    &quot;exn-handler-1-fail-TASK-null&quot;:  {
      &quot;nodes&quot;:  {
        &quot;0-entrypoint-ENTRYPOINT&quot;:  {
          &quot;outgoingEdges&quot;:  [
            {
              &quot;sinkNodeName&quot;:  &quot;1-my-task-TASK&quot;,
              &quot;variableMutations&quot;:  []
            }
          ],
          &quot;failureHandlers&quot;:  [],
          &quot;entrypoint&quot;:  {}
        },
        &quot;1-my-task-TASK&quot;:  {
          &quot;outgoingEdges&quot;:  [
            {
              &quot;sinkNodeName&quot;:  &quot;2-exit-EXIT&quot;,
              &quot;variableMutations&quot;:  []
            }
          ],
          &quot;failureHandlers&quot;:  [],
          &quot;task&quot;:  {
            &quot;taskDefId&quot;:  {
              &quot;name&quot;:  &quot;my-task&quot;
            },
            &quot;timeoutSeconds&quot;:  15,
            &quot;retries&quot;:  0,
            &quot;variables&quot;:  []
          }
        },
        &quot;2-exit-EXIT&quot;:  {
          &quot;outgoingEdges&quot;:  [],
          &quot;failureHandlers&quot;:  [],
          &quot;exit&quot;:  {}
        }
      },
      &quot;variableDefs&quot;:  [],
      &quot;interruptDefs&quot;:  []
    },
    &quot;exn-handler-2-fail-new-process-TASK-any-failure&quot;:  {
      &quot;nodes&quot;:  {
        &quot;0-entrypoint-ENTRYPOINT&quot;:  {
          &quot;outgoingEdges&quot;:  [
            {
              &quot;sinkNodeName&quot;:  &quot;1-my-task-TASK&quot;,
              &quot;variableMutations&quot;:  []
            }
          ],
          &quot;failureHandlers&quot;:  [],
          &quot;entrypoint&quot;:  {}
        },
        &quot;1-my-task-TASK&quot;:  {
          &quot;outgoingEdges&quot;:  [
            {
              &quot;sinkNodeName&quot;:  &quot;2-exit-EXIT&quot;,
              &quot;variableMutations&quot;:  []
            }
          ],
          &quot;failureHandlers&quot;:  [],
          &quot;task&quot;:  {
            &quot;taskDefId&quot;:  {
              &quot;name&quot;:  &quot;my-task&quot;
            },
            &quot;timeoutSeconds&quot;:  15,
            &quot;retries&quot;:  0,
            &quot;variables&quot;:  []
          }
        },
        &quot;2-exit-EXIT&quot;:  {
          &quot;outgoingEdges&quot;:  [],
          &quot;failureHandlers&quot;:  [],
          &quot;exit&quot;:  {}
        }
      },
      &quot;variableDefs&quot;:  [],
      &quot;interruptDefs&quot;:  []
    },
    &quot;exn-handler-3-technical-failure-TASK-FAILURE_TYPE_ERROR&quot;:  {
      &quot;nodes&quot;:  {
        &quot;0-entrypoint-ENTRYPOINT&quot;:  {
          &quot;outgoingEdges&quot;:  [
            {
              &quot;sinkNodeName&quot;:  &quot;1-my-task-TASK&quot;,
              &quot;variableMutations&quot;:  []
            }
          ],
          &quot;failureHandlers&quot;:  [],
          &quot;entrypoint&quot;:  {}
        },
        &quot;1-my-task-TASK&quot;:  {
          &quot;outgoingEdges&quot;:  [
            {
              &quot;sinkNodeName&quot;:  &quot;2-exit-EXIT&quot;,
              &quot;variableMutations&quot;:  []
            }
          ],
          &quot;failureHandlers&quot;:  [],
          &quot;task&quot;:  {
            &quot;taskDefId&quot;:  {
              &quot;name&quot;:  &quot;my-task&quot;
            },
            &quot;timeoutSeconds&quot;:  15,
            &quot;retries&quot;:  0,
            &quot;variables&quot;:  []
          }
        },
        &quot;2-exit-EXIT&quot;:  {
          &quot;outgoingEdges&quot;:  [],
          &quot;failureHandlers&quot;:  [],
          &quot;exit&quot;:  {}
        }
      },
      &quot;variableDefs&quot;:  [],
      &quot;interruptDefs&quot;:  []
    }
  },
  &quot;entrypointThreadName&quot;:  &quot;entrypoint&quot;
}
</pre>`
This is the wfRun that handle Business Exceptions and Technical Errors with: 

`{
  "id":  {
    "id":  "0fe8e9dbe54748d9a01876430bdfd113"
  },
  "wfSpecId":  {
    "name":  "example-exception-handler",
    "majorVersion":  0,
    "revision":  3
  },
  "oldWfSpecVersions":  [],
  "status":  "COMPLETED",
  "greatestThreadrunNumber":  3,
  "startTime":  "2024-11-27T21:39:28.142Z",
  "endTime":  "2024-11-27T21:39:28.175Z",
  "threadRuns":  [
    {
      "wfSpecId":  {
        "name":  "example-exception-handler",
        "majorVersion":  0,
        "revision":  3
      },
      "number":  0,
      "status":  "COMPLETED",
      "threadSpecName":  "entrypoint",
      "startTime":  "2024-11-27T21:39:28.143Z",
      "endTime":  "2024-11-27T21:39:28.175Z",
      "childThreadIds":  [
        1,
        1,
        2,
        2,
        3,
        3
      ],
      "haltReasons":  [],
      "currentNodePosition":  5,
      "handledFailedChildren":  [],
      "type":  "ENTRYPOINT"
    },
    {
      "wfSpecId":  {
        "name":  "example-exception-handler",
        "majorVersion":  0,
        "revision":  3
      },
      "number":  1,
      "status":  "COMPLETED",
      "threadSpecName":  "exn-handler-1-fail-TASK-null",
      "startTime":  "2024-11-27T21:39:28.148Z",
      "endTime":  "2024-11-27T21:39:28.150Z",
      "childThreadIds":  [],
      "parentThreadId":  0,
      "haltReasons":  [],
      "failureBeingHandled":  {
        "threadRunNumber":  0,
        "nodeRunPosition":  1,
        "failureNumber":  0
      },
      "currentNodePosition":  2,
      "handledFailedChildren":  [],
      "type":  "FAILURE_HANDLER"
    },
    {
      "wfSpecId":  {
        "name":  "example-exception-handler",
        "majorVersion":  0,
        "revision":  3
      },
      "number":  2,
      "status":  "COMPLETED",
      "threadSpecName":  "exn-handler-2-fail-new-process-TASK-any-failure",
      "startTime":  "2024-11-27T21:39:28.157Z",
      "endTime":  "2024-11-27T21:39:28.160Z",
      "childThreadIds":  [],
      "parentThreadId":  0,
      "haltReasons":  [],
      "failureBeingHandled":  {
        "threadRunNumber":  0,
        "nodeRunPosition":  2,
        "failureNumber":  0
      },
      "currentNodePosition":  2,
      "handledFailedChildren":  [],
      "type":  "FAILURE_HANDLER"
    },
    {
      "wfSpecId":  {
        "name":  "example-exception-handler",
        "majorVersion":  0,
        "revision":  3
      },
      "number":  3,
      "status":  "COMPLETED",
      "threadSpecName":  "exn-handler-3-technical-failure-TASK-FAILURE_TYPE_ERROR",
      "startTime":  "2024-11-27T21:39:28.168Z",
      "endTime":  "2024-11-27T21:39:28.171Z",
      "childThreadIds":  [],
      "parentThreadId":  0,
      "haltReasons":  [],
      "failureBeingHandled":  {
        "threadRunNumber":  0,
        "nodeRunPosition":  3,
        "failureNumber":  0
      },
      "currentNodePosition":  2,
      "handledFailedChildren":  [],
      "type":  "FAILURE_HANDLER"
    }
  ],
  "pendingInterrupts":  [],
  "pendingFailures":  []
}
`

**Comment by KarlaCarvajal** [comment]
The example has been tested with a workflow that handles exceptions, handles errors and handles any failure and works successfully

![image](https://github.com/user-attachments/assets/5be267ec-33b3-4972-a09c-57b82b7f382c)
![image](https://github.com/user-attachments/assets/51f25761-9920-429d-a59d-2689cedff660)
