### ISSUE TITLE
Duplicated code to call LH Public API

### ISSUE THREAD

**Issue by diablouma** [littlehorse-enterprises/littlehorse#442]
In some of the pages/api bff methods we are making calls to LH Public API to get different resources, however for some of them we are duplicating the code, analyze if it is worth having an abstraction for the duplicated ones.

ie. if you search for client.getNodeRun text in the project you can see that we are doing exactly the same code in multiple places.

**Comment by coltmcnealy-lh** [comment]
Too old, not sure if done or not; also not worth the effort
