### ISSUE TITLE
Have the dashboard in the OSS project

### ISSUE THREAD

**Issue by diablouma** [littlehorse-enterprises/littlehorse#444]
We need to have the dashboard project available in our OSS project, for that we need to:

* Move the dashboard to the OSS repository, preserving the git history if possible
* Have a proper pipeline for it that build, lint, test the project
* Make the dashboard available in the base image ([~accountid:6412638157f0c028e2f4f468] [~accountid:712020:81267384-751a-49f9-b795-9a53b53f3859] [~accountid:641261ed67102fc717bfcf58] ) is the wording correct for this?

**Comment by coltmcnealy-lh** [comment]
Done
