### ISSUE TITLE
Fix Linting

### ISSUE THREAD

**Issue by diablouma** [littlehorse-enterprises/littlehorse#447]
* -Fix how the linter is working in the project, make it more visible so we can fix issues before pushing the code-
** have the linter in a hook and also in pipelines
** pnpm build linter is throwing different errors than pnpm run lint
** -fix README it should – --fix instead of --fix as the argument for the linter command-
** Fix the issues related with all the rules that are for now ignored in the {{packages/eslint-config-custom/next.js}} analyze if everything can be done in this ticket or if we can split if multiple tickets.

**Comment by coltmcnealy-lh** [comment]
Done
