### ISSUE TITLE
Allow user to filter wfRun by Exception status

### ISSUE THREAD

**Issue by diablouma** [littlehorse-enterprises/littlehorse#449]
Talk with @coltmcnealy-lh about context for this ticket.

Difference between Exception and error in LHStatus Enum. We only support ERROR right now.

Handle it the same way we handle exceptions? 

`EXCEPTION` → business related → Allows to take a different path in the workflow based on the type of exception that was thrown. Currently only 3 node types can throw an exception (taskNode, exitNode, waitForThreadNode because it propagates the Exceptions and the Errors from its children)
`Error` → tech related. ie. error during an if condition → error on your workflow spec, something is broken. → any node type can throw an error.

### Ways to throw exception

* Exit Node with a failureDef on it
   * On the UI we should have an indicator that it can throw a business exception.  (the exclamation mark could work)
* A task worker can (in java) throw LHBusinessException passing some information into it
   * Have some marker on the task run indicating that a business exception has thrown. Maybe information on the right side panel showing the info about the business exception.

Add the ability to search for workflows by the exception status.

*Nice to Have (another ticket)*

* wfRun page → combo box with the thread runs → feature: show the status of the thread run for each of them
* Have a tooltip on each type to explain the definition of each status

**Comment by coltmcnealy-lh** [comment]
We definitely want to do this. Currently, the dashboard doesn't do a good job of helping to debug non-vanilla `WfRun`'s
