### ISSUE TITLE
LHS_OAUTH_SCOPE config

### ISSUE THREAD

**Issue by diablouma** [littlehorse-enterprises/littlehorse#488]

**Comment by coltmcnealy-lh** [comment]
@MateoRojas we had some discussions about this in the past. I am pasting some info that I wrote in Confluence here:

> This is a new config which must be added to address what I perceive as a vulnerability in the current implementation. That is, without this config, what happens if a customer uses an Identity Provider for more than just authenticating for the LittleHorse Cluster?

> Currently, this means two things:

> If a client (person or machine) can get a valid token for any purpose from that Identity Provider, then that client can authenticate as the anonymous Principal to the LittleHorse Cluster.

> An Identity Provider that is re-used across multiple LittleHorse Clusters means that under certain circumstances, a client that has access to Cluster A might accidentally be able to access resources in Cluster B.

### Discussion
> There has been some opposition in Slack to this config being added:

> @MateoRojas  brings up a good point. I agree that it should be an optional config, and that if it is not set, then the LittleHorse Cluster should behave as it did before the config was added.

> I do think it still should be added, for three reasons:

> 1. It is an opt-in config, so it has no impact on customers.
> 2. It will be at most 10 lines of code and as such does not incur a high maintenance cost to us.
> 3. Customers of LH Platform may want to use the same Identity Provider for LittleHorse and also other applications without enabling fine-grained ACL's within LittleHorse itself. This is not safe without `LHS_OAUTH_SCOPE`.

**Comment by coltmcnealy-lh** [comment]
@sauljabin has recommended closing this. I still think it is necessary for LH Platform users who wish to use authentication + the `anonymous` Principal. In that case, it would make sense to have a generic scope just for the LH Server.

Leaving this open, but we will defer it for later.

**Comment by coltmcnealy-lh** [comment]
Closing. This isn't the way OAuth scopes are meant to be used.
