### ISSUE TITLE
Improve `waitForCommand` During Rebalances

### ISSUE THREAD

**Issue by diablouma** [littlehorse-enterprises/littlehorse#497]
Right now, if the following happens:

1. GRPC request comes in
2. Server A sends a `Command` to Kafka, it gets sent to a partition assigned to Server `B`
3. Server A sends a `waitForCommand` internal grpc request to Server `B`
4. Before Server `B` processes the command, a rebalance happens. Now the `Command` gets sent to Server `C`.

then the `rpc waitForCommand` request will just timeout or fail because it’s waiting on the wrong place.

We can improve this. The way to do so is to make the `AsyncWaiters.java` class more intelligent. If it detects that something is waiting for a `Command` that is no longer assigned to Server B, then Server B should do one of the two following strategies:

1. Make a second `waitForCommand` request to Server `C`, and relay the result back to Server `A`, **OR**
2. Immediately send an error back to Server `A`, and Server `A` contacts Server `C` (transparently to the external client)

Somewhat counter-intuitively, I believe that option 1 will be easier to implement. Either one is fine.

**Comment by coltmcnealy-lh** [comment]
@eduwercamacaro do you know if there is a hook we can listen to in order to be notified of changes in the Kafka Streams Task Assignments on each server?

Then we could trigger the logic to start waiting on the correct partition.

**Comment by eduwercamacaro** [comment]
I think we can modify the `WaitForCommandReponse` in order to support the case when the instance that contains the `CommandWaiter` loses the partition ownership associated to that command .

`message WaitForCommandResponse {
    string command_id = 1;
    google.protobuf.Timestamp result_time = 2;
    message NotOnThisInstanceException {
        LHHostInfo new_instance = 1;
    }
    oneof yield {
        bytes result = 3;
        NotOnThisInstanceException not_on_this_instance_exception = 4;
    }
}`

We will listen the kafka streams `RUNNING` state, and we will check every `CommandWaiter` and send the `NotOnThisInstanceException`  on the onNext
