### ISSUE TITLE
Improve GRPC Server Shutdown

### ISSUE THREAD

**Issue by diablouma** [littlehorse-enterprises/littlehorse#498]
Currently, we use {{server.shutdownNow()}} (Call train: {{ServerListener.java}} ← {{ListenersManager.java}} ← {{KafkaStreamsServerImpl.java}})

This terminates all in-flight grpc requests, especially Streaming requests. The Task Workers use bi-directional stream requests.

We should:

# Determine whether the abrupt closing of the connection causes any issues.
# If issues are present, we should implement a protocol wherein the server sends a “hey, it’s over” request to the Task Worker, and the Task Worker gracefully handles the response.

**Comment by coltmcnealy-lh** [comment]
After a thorough investigation, `shutdownNow()` is the correct choice. We already have retries using the bootstrap host in the Task WOrker SDK. That covers the long-running connection issue.

Additionally, the Task Worker uses two different rpc's (`ReportTask` and `PollTask`) and only `PollTask` is a streaming RPC, so properly closing streams wouldn't even help.
