### ISSUE TITLE
BUG: Why ERROR not EXCEPTION

### ISSUE THREAD

**Issue by diablouma** [littlehorse-enterprises/littlehorse#515]
Look at this diff in the PR. Before, the e2e-test was checking for incorrect behavvior. Correct status is {{COMPLETED}}, but in {{HandlingFailureThreadHaltReason}} line 42, we forgot to check for {{EXCEPTION}} status:

{noformat}if (wft.getThreadStatus() == LHStatus.ERROR) {{noformat}

Edu fixed that bug in his PR, linked below.

However, note that the status was {{ERROR}} not {{EXCEPTION}}. It should have been {{EXCEPTION}}. WTF?

[https://github.com/littlehorse-enterprises/littlehorse/pull/107/files#diff-5a1e261261613e2680cedcc0376a38d1ecf07ea1e7df48abae0ab85a18d6d483L147|https://github.com/littlehorse-enterprises/littlehorse/pull/107/files#diff-5a1e261261613e2680cedcc0376a38d1ecf07ea1e7df48abae0ab85a18d6d483L147|smart-link]

**Comment by coltmcnealy-lh** [comment]
Already fixed
