### ISSUE TITLE
Test Weird `INVALID_ARGUMENT` when killing server

### ISSUE THREAD

**Issue by diablouma** [littlehorse-enterprises/littlehorse#517]
To reproduce:

* Set log level `debug`
* Run 100 instances of `hundred-tasks` wf
* `kill -9` the Server java process
* When starting the server back up, you’ll see some `INVALID_ARGUMENT` exceptions saying “Task Run not found”. These are highly suspicious and from my understanding of the code path they imply  data loss. We should investigate.

**Comment by coltmcnealy-lh** [comment]
@eduwercamacaro I think we should take a look at this together. Maybe it's related to your investigation in #557 ?

**Comment by coltmcnealy-lh** [comment]
Further investigation has yielded that the current `master` branch behaves correctly. Any uncommitted changes in rocksdb are wiped, and in-flight TaskClaimEvent's are rejected.
