### ISSUE TITLE
Task Worker Health Visibility

### ISSUE THREAD

**Issue by diablouma** [littlehorse-enterprises/littlehorse#520]
All four Task Worker implementations should have a method which returns the status of the worker, used for health checking. It should be determined by whether the main thread (rebalance thread) can contact the LH Server.

* On GRPC connection lost or on a rebalancing, the client app should not die.
* We need a configurable timeout for the hearth beat, if that timeout is over, the client app can die, right now it dies as soon as the connection is lost.
* Add any change to all the sdks.

**Comment by coltmcnealy-lh** [comment]
Done already
