### ISSUE TITLE
Allow UserTask to throw Exception on Timeout

### ISSUE THREAD

**Issue by diablouma** [littlehorse-enterprises/littlehorse#527]
Current experience: I’m not sure if it’s possible to put a timeout on a User Task Run.

Desired experience: Can do something like:

{noformat}UserTaskOutput uto = thread.assignTaskToUser(...);

thread.cancelUserTaskAfter(uto, 60 * 60, "too-lazy-to-finish-task");{noformat}

**Comment by coltmcnealy-lh** [comment]
Closing as duplicate of #599
