### ISSUE TITLE
Update License to Apache2 for Clients

### ISSUE THREAD

**Issue by coltmcnealy-lh** [littlehorse-enterprises/littlehorse#549]
### Context

Move the clients to the Apache 2.0 License, but the server, dashboard, and docker images should remain SSPL.

### Acceptance Criteria

- Migrate Java Maven
- Migrate Python Pypi
- Go
- MIgrate .NET Nuget
- Add new Licence
- Update the LICENSE.md with a note

### Out of Scope

Server

### Open Questions

Do we need to put a license on top of every file?

**Comment by sauljabin** [comment]
**SSPL**
dashboard
server

**APACHE**
go
python
java
dotnet
lhctl
examples
schemas
test-utils

**Comment by eduwercamacaro** [comment]
We should add license description on opensource classes

**Comment by coltmcnealy-lh** [comment]
Closing this as "not planned" for now. SSPL license and Apache2 license for clients don't have a material difference; no one has complained about it; and it would be a lot of work and quite a bit of confusion.

IF someone complains about it we can do this later in the future. For now having everything under SSPL is super easy.
