### ISSUE TITLE
Rehydrate Tasks from Task Queue in Multi-Tenancy

### ISSUE THREAD

**Issue by coltmcnealy-lh** [littlehorse-enterprises/littlehorse#557]
### Context

When an LH Server shuts down, it does not rehydrate previously-scheduled tasks from outside the `default` tenant onto the Task Queue.

### Steps To Reproduce

1. Run LH with multiple tenants.
2. Run a `WfRun` in a tenant other than `default`
3. Do NOT schedule a task worker.
4. Kill and restart the Server
5. Start the Task Worker

The `TaskRun` will stay in the `TASK_SCHEDULED` state but will never be delivered to the Task Worker, and the `WfRun` will be blocked.

### Expected Behavior

The `CommandProcessor#onPartitionClaimed()`, correctly iterates through all `ScheduledTask` entries in the data store, and puts them onto the internal in-memory task queue for the server, but *ONLY* in the `default` tenant.

We need to re-hydrate the task queues for *all* tenants.

### Additional Context

To solve this, we need to iterate through all tenants, and then for each tenant we need to perform the iteration we are currently already performing.

This ticket also relates to #490 . I believe that both tickets can be addressed in the same PR.

### Components

- [ ] Dashboard
- [X] Server
- [ ] Python SDK
- [ ] Go SDK
- [ ] Java SDK
- [ ] C# SDK
- [ ] LH Control
- [ ] LH Tests Utils

**Comment by eduwercamacaro** [comment]
There is a report which says that we can get a similar behavior even with a single tenant. We need to verify this as well.

**Comment by eduwercamacaro** [comment]
I think that `ScheduledTaskModel` should be saved in the DefaultStore. To do this, we should switch to the specific DefaultStore instead of the ModelStore. Or just wait until https://github.com/littlehorse-enterprises/littlehorse/pull/556 gets merged

**Comment by eduwercamacaro** [comment]
Update: 
We're looking to use TenantStore to make ScheduledTask totally separate by renter after we talk about this. To do this, a range scan of the refresh process is needed. This is okay, though, since it is only called at startup.
cc: @coltmcnealy-lh
