### ISSUE TITLE
Measure Metrics Aggregator performance.

### ISSUE THREAD

**Issue by eduwercamacaro** [littlehorse-enterprises/littlehorse#576]
### Context

Workflow metrics are calculated on a per-partition basis and then aggregated into a repartition store (see PartitionMetricsModel). To avoid sending many records into the repartition topic, we send the partition metrics every 30 seconds via Kafka Streams Punctuator. It is important to mention that punctuators execute blocking operations over the CoreProcessor, so it is mandatory to keep this as performant as possible to avoid hurting latency for commands. We need a way to verify that we meet performance expectations and weird behaviors under high-load scenarios.

We should ensure that any necessary changes do not impact metric calculations since they need to be accurate.

### Value

Low

### Effort

High

### Current State and Pains

We need to test LH server under high load scenarios and make sure that we meet performance expectations.

### Solution and Benefits

It will depend on the diagnosis.

### Acceptance Criteria

**Scenario** [the name for the behavior that will be described]
**Given** [the beginning state of the scenario]
**When** [specific action that the user makes]
**Then** [the outcome of the action in **When**]
**And** [used to continue any of three previous statements]

### Components

- [ ] Dashboard
- [X] Server
- [ ] Python SDK
- [ ] Go SDK
- [ ] Java SDK
- [ ] C# SDK
- [ ] LH Control
- [ ] LH Tests Utils

**Comment by coltmcnealy-lh** [comment]
I did some benchmarking.

One terminal:
```
gradle example-hundred-tasks:run
```

Another terminal:
```
-> for i in $(seq 1 1000) ; do lhctl run hundred-tasks ; done
```

Wait for the last WfRun to finish.

With current `master` branch: 6 minutes 6 seconds.

Then I disabled the `MetricsUpdater#listen()` method and made it a no-op. 1 minute, 59 seconds.

We will rewrite this with the original proposed implementation.

**Comment by coltmcnealy-lh** [comment]
This spike is closed; we are rewriting the Metrics Aggregator
