### ISSUE TITLE
StackOverflow when a NodeOutput is used as a variable by mistake

### ISSUE THREAD

**Issue by eduwercamacaro** [littlehorse-enterprises/littlehorse#596]
### Context

```
TaskNodeOutput nodeOutput = createUserThread.execute("find-current-user", newUser.jsonPath("$.id"));
WfRunVariable existingUser = createUserThread.addVariable("existing-user", nodeOutput);
```

An StackOverflow is produced after running above example. That example is passing a `nodeOutput` example as variable value.

### Steps To Reproduce

Create a WfSpec which contains something similar to this:
```
TaskNodeOutput nodeOutput = createUserThread.execute("find-current-user", newUser.jsonPath("$.id"));
WfRunVariable existingUser = createUserThread.addVariable("existing-user", nodeOutput);
```

### Expected Behavior

Runtime exception should be thrown.

### Additional Context

Verify if this behavior is present in other SDKs

### Components

- [ ] Dashboard
- [ ] Server
- [ ] Python SDK
- [ ] Go SDK
- [X] Java SDK
- [ ] C# SDK
- [ ] LH Control
- [ ] LH Tests Utils

**Comment by coltmcnealy-lh** [comment]
Need to check other SDK's too

**Comment by coltmcnealy-lh** [comment]
Oops didnt mean to close
