### ISSUE TITLE
Throw `EXCEPTION` on `CANCELLED` User Task Runs

### ISSUE THREAD

**Issue by coltmcnealy-lh** [littlehorse-enterprises/littlehorse#599]
### Context

Currently, when a `UserTaskRun` is cancelled, the result is undefined. We do not have tests for it, and our documentation is conflicting + unclear.

### Description

When a `UserTaskRun` is cancelled, it represents a Business Process Failure and not a Technical `ERROR`. Therefore, it should use the `EXCEPTION` status and not the `ERROR` status. Currently, I believe it uses the `ERROR` status.

One thing to note is that in the server (this is also not documented yet), all `ERROR` names are pre-defined by the LH Server and use `UPPER_UNDERSCORE_CASE`. All `EXCEPTION` names are defined by the user and use `kebab-case`. The case of a `UserTaskRun` being cancelled is an interesting one, because it is initially not obvious how we should handle the naming of the `Failure`.

A `WfSpec` might want to treat a Cancelled UserTaskRun as a _specific_ `EXCEPTION`, for example treat it the same as a `no-approval` Exception thrown when the output of the `UserTaskRun` is "no, not approved".

I propose that we should:
* Allow a `WfSpec` to specify that a `UserTaskRun` should be cancelled after a certain period of time passes (either after reassignment or after creation), via `WorkflowThread#cancelUserTaskAfter(...)`
* Allow the `UserTaskNode` to specify an `EXCEPTION` name that should be thrown if cancelled.
* Choose a default exception to throw when not specified (for compatibility)

### Acceptance Criteria

* All SDK's should have `WorkflowThread#cancelUserTaskAfter()` or `UserTaskNodeOutput#cancelAfter()`
* `UserTaskNode` defines an `EXCEPTION` to be thrown when the task is cancelled
* There is a default `EXCEPTIOn` to be thrown for backwards compatibility

**Comment by eduwercamacaro** [comment]
I suggest avoid guessing an business exception name when it is not specified. It should be an ERROR because it is a not handled business path.

**Comment by coltmcnealy-lh** [comment]
After some further discussions, I think the behavior we will have is as follows:
* Allow the user to optionally specify an `EXCEPTION` to throw upon cancellation of the `UserTaskRun`.
* If the user does NOT specify an `EXCEPTION`, we keep the current behavior of using the `LHErrorType.USER_TASK_CANCELLED`, which is treated as an `ERROR` by LH.

Note: there are a few differences between `ERROR` and `EXCEPTION`:
* When a child thread fails with `ERROR`, the parent receives a failure `LHErrorType.CHILD_FAILURE`.
* When a child thread fails with `EXCEPTION`, the parent receives the same `Failure` thrown by the child.
