### ISSUE TITLE
Refactor and remove duplicated component TaskExecutionMetrics.tsx

### ISSUE THREAD

**Issue by mijailr** [littlehorse-enterprises/littlehorse#676]
## Context

The component `TaskExecutionMetrics.tsx` has a dup sibling component at task level that should be removed, also the component is quite complex and has a lot of responsibilities error prone and it's not taking advantage of server side rendering.

**Comment by coltmcnealy-lh** [comment]
Let's put this on hold, because the "Metrics API" is not considered stable and is highly likely to change in the next few weeks.
