### ISSUE TITLE
Search available tenants

### ISSUE THREAD

**Issue by mijailr** [littlehorse-enterprises/littlehorse#692]
### Context

Something like this might work

```proto
rpc SearchTenant(SearchTenantRequest) returns (TenantIdList) {}

message SearchTenant {
  int32 limit = 1;
  optional bytes bookmark = 2;
}

message TenantIdList {
  repeated TenantId tenants = 1;
  optional bytes bookmark = 2;
}
```

### Acceptance Criteria

Should return the list of tenants if the principal has `global_acls` permissions.

**Comment by coltmcnealy-lh** [comment]
This should require the acl `READ` over `TENANT` in the `global_acls` field of the `Principal` making the call.

**Comment by coltmcnealy-lh** [comment]
After thinking further, I think we may need to extend the way the `@Authorize` decorator works. Maybe @eduwercamacaro can weigh in on this tomorrow.

**Comment by jhosep-marin** [comment]
In the end, the team decided to keep this as follows:

`rpc SearchTenant(SearchTenantRequest) returns (TenantIdList) {}`
