### ISSUE TITLE
Enhancements for `UserTaskRun` on Dashboard

### ISSUE THREAD

**Issue by coltmcnealy-lh** [littlehorse-enterprises/littlehorse#787]
When clicking on a `UserTaskRun` node in the dashboard, I would like to see the following information:

- [x] - Who is it currently assigned to? (`user_group` and/or `user_id`)_
- [x] - The "Audit Log" which is the `events` field of the `UserTaskRun` 
- [x]   - Assignment history and/or cancellation history
- [x] - If it has a specific `EXCEPTION` that it throws upon cancellation
- [x] - The `results` after it is completed
- [x] - When the `UserTaskRun` was created (i.e. arrival time)
- [x] - When the `UserTaskRun` was completed or cancelled (if it isn't still pending)

**Comment by diablouma** [comment]
Code already merged in master

**Comment by diablouma** [comment]
Code already merged in master
