### ISSUE TITLE
`UserTaskRun` Search on the Dashboard

### ISSUE THREAD

**Issue by coltmcnealy-lh** [littlehorse-enterprises/littlehorse#788]
On the `UserTaskDef` page, we should be able to search for `UserTaskRun`'s of that type. We should be able to filter by:

- The `status`
- Assigned `userId`
- Assigned `userGroup`
- Created time

Clicking on the result should take you to the relevant `WfRun` and also highlight the appropriate `NodeRun` on that `WfRun`.

**Comment by diablouma** [comment]
@coltmcnealy-lh, do you want those filters to work together? I mean, If I search by status and then I type a user Id, should those 2 filter be applied?
