### ISSUE TITLE
Dashboard: Show Variables on the `WfRun`

### ISSUE THREAD

**Issue by coltmcnealy-lh** [littlehorse-enterprises/littlehorse#790]
On the `WfRun` page, we should be able to see all `Variable`s for the highlighted `ThreadRun`, including their name, type, and value.

To implement this, you can use the `rpc ListVariables` and pass in the specific `thread_run_number`.

It should expose a `VariablesContext` so the values are easy to access from any child component (ex: Nodes) this will simplify the implementation of #804

**Comment by mijailr** [comment]
@diablouma
