### ISSUE TITLE
Add `rpc SearchPrincipal`

### ISSUE THREAD

**Issue by coltmcnealy-lh** [littlehorse-enterprises/littlehorse#836]
Should follow the standard API patterns of taking in a `SearchPrincipalRequest` and returning a `PrincipalIdList`.

Should be able to search by:
- `isAdmin`
- `tenant`
- `createdAt`

All search values should be optional.

**Comment by coltmcnealy-lh** [comment]
@eduwercamacaro how should we handle permissions here? If I have the following acl's:

```
{
 per_tenant_acls: {
   my-tenant: {
     actions: ALL_ACTIONS,
     resource: ALL_RESOURCES
   }
 }
}
```

should that `Principal` be able to execute the `rpc SearchPrincipal`? There are three options:

1. Return `PERMISSION_DENIED`
2. Return all `Principal`s with `per_tenant_acls` in the `my-tenant` Tenant
3. Return all `Principals` with `per_tenant_acls` in the `my-tenant` Tenant _and also_ any admin Principals

From the perspective of LittleHorse Cloud, I think option 2 is the best.

**Comment by coltmcnealy-lh** [comment]
@Snarr what do you think?

**Comment by eduwercamacaro** [comment]
I think we should go with option 2

**Comment by Snarr** [comment]
After talking it over with Eduwer, I agree option 2 sounds the best.
