### ISSUE TITLE
Support THROW_EVENT node type on Dashboard

### ISSUE THREAD

**Issue by coltmcnealy-lh** [littlehorse-enterprises/littlehorse#882]
We should render the `WorkflowEventNode` and `WorkflowEventNodeRun` properly. Right now, the `WorkflowEventNode` is just a gray box. It should be something like a BPMN Throw Event (darker circle than the Catch Event, which is like our normal `ExternalEventNode`).

Right now, going to a `WfRun` that has a `WorkflowEventNode` in it causes a crash. That's not good.

On the `WorkflowEventNode`, we should see:
- The `WorkflowEventDefId`
- The Variable Assignment that determines the content of the event to be thrown (like TaskDef Input Parameters)

On the `WorkflowEventRun`, we should see:
- The `WorkflowEventDefId`
- The content of the thrown `WorkflowEvent`
- The `id` of the `WorkflowEvent` that was thrown

**Comment by eduwercamacaro** [comment]
I guess that `WorkflowEventNode` is a `ThrowEventNode`. correct? I think we need to update this issue

**Comment by Snarr** [comment]
Closed, fixed by PR #1061
