### ISSUE TITLE
Users able to reveal Tenants they are not assigned to

### ISSUE THREAD

**Issue by Snarr** [littlehorse-enterprises/littlehorse#901]
### Context

A user with the `ALL_RESOURCES` ACL can search for and reveal the existence of tenants even when they are not assigned to them.

### Steps To Reproduce

1. Create a Principal that has the `ACL_ALL_RESOURCES` ACL permission scoped to a specific tenant (example: test).
2. Create another tenant within the same `lhCluster` that the new Principal does not have access to.
3. Run a `SearchTenant` request as the Principal defined in Step 1.
4. BUG: Server returns both tenants, including the one the Principal is assigned to AND the one the Principal is not assigned to

### Expected Behavior

A non-admin user with the `ACL_ALL_RESOURCES` perTenantAcl that runs a SearchTenant request should receive a PERMISSION_DENIED error. Cluster-scoped resources are not available to Principals using perTenantAcls, to protect the privacy of other tenants within the same cluster.

### Components

Server

**Comment by coltmcnealy-lh** [comment]
Jacob finished it
